name: Generate and Publish Javadocs

on:
  push:
    branches:
      - main  # O cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Cambia la versión según tu proyecto

      - name: Generate Javadocs
        run: ./gradlew javadoc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/docs/javadoc  # Ruta donde están los Javadocs
          clean: true  # Borra archivos viejos antes de subir los nuevos
